function resp(){
    document.getElementById("res1").innerHTML = "La distancia es: "+ distancia_1(3.5);
}
function distancia_1(a){
    //Paso 1: Cargar las coordenadas.
    x1=2
    x2=3
    y1=5
    y2=6
    dis=((x2-x1)**2+(y2-y1)**2)**0.5
    //Retorno el valor calculado(distancia entre dos puntos).
    return(dis);
}

function resp2(){
    document.getElementById("res2").innerHTML = "La distancia es: "+distancia_2(3.5);
}
function distancia_2(a){
    x1=6
    x2=8
    y1=4
    y2=9
    dis=((x2-x1)**2+(y2-y1)**2)**0.5
    return(dis);
}

function resp3(){
    document.getElementById("res3").innerHTML = "La distancia es: "+distancia_3(3.5);
}
function distancia_3(a){
    x1=1
    x2=4
    y1=3
    y2=9
    dis=((x2-x1)**2+(y2-y1)**2)**0.5
    return(dis);
}

function resp4(){
    document.getElementById("res4").innerHTML = "La distancia es: "+distancia_4(3.5);
}
function distancia_4(a){
    x1=7
    x2=6
    y1=9
    y2=1
    dis=((x2-x1)**2+(y2-y1)**2)**0.5
    return(dis);
}

function resp5(){
    document.getElementById("res5").innerHTML = "La distancia es: "+distancia_5(3.5);
}
function distancia_5(a){
    x1=5
    x2=2
    y1=7
    y2=9
    dis=((x2-x1)**2+(y2-y1)**2)**0.5
    return(dis);
}

function resp6(){
    document.getElementById("res6").innerHTML = "La distancia es: "+distancia_6(3.5);
}
function distancia_6(a){
    x1=1
    x2=8
    y1=3
    y2=6
    dis=((x2-x1)**2+(y2-y1)**2)**0.5
    return(dis);
}

function resp7(){
    document.getElementById("res7").innerHTML = "La distancia es: "+distancia_7(3.5);
}
function distancia_7(a){
    x1=6
    x2=1
    y1=8
    y2=6
    dis=((x2-x1)**2+(y2-y1)**2)**0.5
    return(dis);
}

function resp8(){
    document.getElementById("res8").innerHTML = "La distancia es: "+distancia_8(3.5);
}
function distancia_8(a){
    x1=4
    x2=3
    y1=5
    y2=8
    dis=((x2-x1)**2+(y2-y1)**2)**0.5
    return(dis);
}

function resp9(){
    document.getElementById("res9").innerHTML = "La distancia es: "+distancia_9(3.5);
}
function distancia_9(a){
    x1=1
    x2=9
    y1=5
    y2=6
    dis=((x2-x1)**2+(y2-y1)**2)**0.5
    return(dis);
}

function resp10(){
    document.getElementById("res10").innerHTML = "La distancia es: "+distancia_10(3.5);
}
function distancia_10(a){
    x1=8
    x2=2
    y1=4
    y2=6
    dis=((x2-x1)**2+(y2-y1)**2)**0.5
    return(dis);
}

function resp11(){
    document.getElementById("res11").innerHTML = "La distancia es: "+distancia_11(3.5);
}
function distancia_11(a){
    x1=0
    x2=400
    y1=0
    y2=400
    dis=((x2-x1)**2+(y2-y1)**2)**0.5
    return(dis);
}